### ISSUE TITLE
[FEATURE] Any plans for bottom style theme ?

### ISSUE THREAD

**Issue by Akianonymus** [jrolfs/gruvbox-material-tridactyl#3]
Or refrences to the code i need to change.

**Comment by jrolfs** [comment]
I would definitely be open to this. I can try and point you in the right direction if you're interested in working on it.

**Comment by Akianonymus** [comment]
Aah, thank you for considering, but i now that i tried it, top seems more natural to me. I hacked my way to bottom style, animation was too distracting ( maybe there is a better way to do it ).

By the way, great theme.

I did some changes, is it worth enough to pr ? Also, any way to wrap the help text and show on next line ( maybe that would be to horrific to look at )

![image](https://user-images.githubusercontent.com/32216346/182199519-f61a4c5d-d043-4bc7-8897-be6b11ca5ed0.png)

**Comment by jrolfs** [comment]
> Also, any way to wrap the help text and show on next line ( maybe that would be to horrific to look at )

This feels worth at least exploring... it's kinda lame we truncate all that information currently, but I'm not sure what the ideal solution is here.
