### ISSUE TITLE
How to reset to use default hint color config?

### ISSUE THREAD

**Issue by lost22git** [jrolfs/gruvbox-material-tridactyl#5]
I found that the hint color of the current theme makes it difficult for me to recognize the hint chars, so I wonder if there is a way to use the default hint colors (fg:white bg:blue) 

![Screenshot 2023-05-24 at 09-08-03 New Issue · jrolfs_gruvbox-material-tridactyl](https://github.com/jrolfs/gruvbox-material-tridactyl/assets/65008815/a91a02a1-7601-4c55-b4c1-9596ce17e884)

**Comment by jrolfs** [comment]
Do you mean the contrast on the text isn't high enough? As far as I know, there isn't really a way to pass configuration to the theme. I can try to create a high-contrast variant when I have time.

**Comment by lost22git** [comment]
Hi @jrolfs , sorry for taking so long to reply, it would be great if there is a high contrast version, thanks ;-)
